spring:
  data:
    mongodb:
      uri: mongodb+srv://stsahilvarma04_db_user:82vdtB9DSPb2gLVD@cluster0.xufvgz0.mongodb.net/?appName=Cluster0
      database: farmtocloud
      auto-index-creation: true

server:
  port: 8080

app:
  jwt:
    secret: farmToCloudSuperSecretKeyThatIsLongEnoughForHS256Algorithm2024
    expiration-ms: 86400000